services:
  - type: web
    name: campus-buddy-server
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FIREBASE_PROJECT_ID
        value: campusbuddy-f5592
      - key: FIREBASE_PRIVATE_KEY_ID
        value: 928a40d70d657cca0c53791f49e460ce97f2ab63
      - key: FIREBASE_PRIVATE_KEY
        value: "-----BEGIN PRIVATE KEY-----\nMIIEugIBADANBgkqhkiG9w0BAQEFAASCBKQwggSgAgEAAoIBAQDfnONb/vgNbG2S\nXHefUbqCYv6wihVpBc23N289sM//raMxrGGJ6aiTVr8USnaUxu9xqSBe5XmuGsCk\nK6ffZKkwwNgf5HGcbsUi3kN92u87fhY7FbuQbeA5RBOtw8uLwEgZTASWDbgx/6rr\n6Ty/QmySF3+qZVgmOz0MT6AJ8M95bOdLzPmoBpqPHD2VEGHnNRZ3DgoKb9GCO0Pj\nn2eLYhLGfGy8PR/TosBVxX+Pz7EPhchCjFHjKU51NMlabaZsX9hhOlGrZuXvcUge\n0SMW5ftm6sJ4Q0fwzz2vl+PUPK4qTlfGwjtjs+5JN7b1BpPtFGh9H0WoMuGfeqQA\nhIi/R+OhAgMBAAECgf9LExrmQlmSj7lwji2mzN9LvxkT3riFQMVKn91yw0Hm+LzN\nYjafV55Cywx43te9XbmZDDw4HqJBdHH/b/ZpuCFPOLHKJduGJAaHZ+chUt0Y6eoz\npDOYbffsoPibfJV8lsLO/ZthbHkKppxhZETz93GY6JKzfsYMqz5lEFDrpo2DLx0i\nmE4CnZU3zQRHm7lY8Gn5rftpwSQK0f28tjonctNOBvs7d1Y8Eln7c3YHfQrkGhro\nVhT4Ld1gPwKXvpV3rtgt9tlj7072gelgRJGmz5A2NTUdalzN/JDTDqlnf5YyLd5l\nthyQHuXS72fY1Whh/Tkf+VbvnDZjW5G58/Ag0s8CgYEA+I4E8B1w+gckRqiT87yT\n7Ew/a29WKFbSHiKyCQsJV6Lvk3cCTiKbBKrZdowJGngCc9oI0OVt7a84C62i7pq5\nqCkZLiPLVunaq6fZ0R/Un3DtOyBdgBRpv8knnpLd5zJB+AYRp1lEYB3TNbB+3kgG\n+VaY2Xlw0Z9fpmhSGMZWGqMCgYEA5k+bn2QiizlEhbfwmOakazq+Ja8T7ZxxGLb8\nTQvlbxXVL+CvpQSzU1wx+zOmJXvKdP4hvzKq69QqJHpWEGzfvc5X8BcNL9BW8nw4\noEPYnObkgJNeddUIEnNiJ81rBOvtl9CqYJbWbjCkdgkziUKEW+K4k719kRn3ed86\n6q+T0OsCgYAib8rPWcTlX0fvYjvdcSstegLvZ6WQQTcrZbM0/Yp10eVPkRWIrdK8\nes9WVWCNgkMUugiuqJrqa3gadZBKL7ARbFvaxYpHI1nawIKr1ZOIN89aeaKcEmW\ngNA0cDS+a4AoVO7tOLj4eCljLujk8yXENfNHbkPrRyGBdMKrHA+h8QKBgCZkjO/E\nNJH66PZVlHEYub36W+pSRkMs+hmBn4uEeSnMfO5vSTh8ERzLWLWkhYToHvbjymJi\nIuYPRzsvfZtdWur8M+KdJSCcXXIszQ/CX6DASMU6S9veuGrC+1DhSH7YiZHuQgi5\n/GMADtpybDnscb4TjGtsgjsnFf8l/F9VB5IjAoGAAtWX8Fx7SgOesBHpFy8328lI\nPNuJ5jFI+8FJoQvq93t1CEm8c7MviZ65MwwGCed/Dn+yfxiUFM3brTfa2pDVbNJU\nMJZIO5CRT6F9sgUV4xrb4xpupLAa/MiR7x+ZpE4FUmZjTzC0xiwvU8wi11l2m1Uk\nrt8cF6hyTmmFa0OuF6Y=\n-----END PRIVATE KEY-----\n"
      - key: FIREBASE_CLIENT_EMAIL
        value: firebase-adminsdk-fbsvc@campusbuddy-f5592.iam.gserviceaccount.com
      - key: FIREBASE_CLIENT_ID
        value: 106533933285880726551
      - key: FIREBASE_AUTH_URI
        value: https://accounts.google.com/o/oauth2/auth
      - key: FIREBASE_TOKEN_URI
        value: https://oauth2.googleapis.com/token
      - key: JWT_SECRET
        value: campus-buddy-super-secret-jwt-key-2024
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CORS_ORIGIN
        value: https://campus-buddy123.vercel.app
